language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"
before_script: sudo apt-get install pychecker pylint pep8 rpm python-rpm
install:
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm # see https://github.com/travis-ci/travis-cookbooks/issues/155
  - pip install pybuilder --use-mirrors
  - pip install coveralls
  - pyb --debug install_dependencies
script: "pyb --debug -v verify && coverage run --source=src/main/python/livestatus_service `which pyb` run_unit_tests"
after_success:
  - coveralls --verbose
