language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
before_script: sudo apt-get install pychecker pylint pep8 rpm python-rpm
install:
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm # see https://github.com/travis-ci/travis-cookbooks/issues/155
  - pip install pybuilder
  - pip install coveralls
  - pyb --debug install_dependencies
script: "pyb"
after_success:
  - coveralls --verbose
